CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE accounts(id TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE broker_profiles(id TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE providers(id TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE provider_metrics(id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES providers(id), date TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE provider_status(id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES providers(id), payload TEXT NOT NULL);
CREATE TABLE provider_drawdowns(id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES providers(id), payload TEXT NOT NULL);
CREATE TABLE provider_daily_performance(id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES providers(id), date TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE signals(id TEXT PRIMARY KEY, provider_id TEXT, account_profile TEXT, timestamp TEXT NOT NULL, raw_payload TEXT NOT NULL, normalized_payload TEXT NOT NULL, validation_status TEXT NOT NULL, rejection_reason TEXT);
CREATE TABLE decisions(id TEXT PRIMARY KEY, signal_id TEXT, account_profile TEXT, timestamp TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE signal_outcomes(id TEXT PRIMARY KEY, signal_id TEXT NOT NULL, account_profile TEXT NOT NULL, status TEXT NOT NULL, payload TEXT NOT NULL);
CREATE UNIQUE INDEX one_outcome_per_signal_account ON signal_outcomes(signal_id,account_profile);
CREATE TABLE positions(id TEXT PRIMARY KEY, account_profile TEXT NOT NULL REFERENCES accounts(id), provider_id TEXT NOT NULL REFERENCES providers(id), signal_id TEXT NOT NULL, status TEXT NOT NULL, payload TEXT NOT NULL);
CREATE UNIQUE INDEX one_open_position ON positions(account_profile) WHERE status='OPEN';
CREATE TABLE withdrawal_tests(id TEXT PRIMARY KEY, broker_profile_id TEXT NOT NULL REFERENCES broker_profiles(id), payload TEXT NOT NULL);
CREATE TABLE strategies(id TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE backtests(id TEXT PRIMARY KEY, strategy_id TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp TEXT NOT NULL, event TEXT NOT NULL, payload TEXT NOT NULL, previous_hash TEXT NOT NULL, hash TEXT NOT NULL);
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_logs BEGIN SELECT RAISE(ABORT,'Audit log is append-only'); END;
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_logs BEGIN SELECT RAISE(ABORT,'Audit log is append-only'); END;
INSERT INTO schema_migrations VALUES(1, strftime('%Y-%m-%dT%H:%M:%SZ','now'));
